# Site settings 配置站点
title: 'Blog of Cauchy'
description: 'There is no web description temporarily.'
keywords: 'unity'
url: 'https://Cauchyoooo.github.io' # your host

# 导航栏 nav 中文字符空格：&emsp;
nav: # 最佳体验 六个标签 且最好每个标签不超过4中文字
  首页: '/'
  标签: '/tags.html'
  时间线: '/timeline.html'
  关于博主: '/about.html'
  友情链接: '/friendLink.html'

# 博主
author: true
name: 'Ekin'
NickName: 'Cauchy'
webtitle: "Cauchy's Blog"
bio: 'A Student.'
about: true
aboutyou: "A junior in SYSU."
portraits: '/assets/profile.jpg' # your portraits image file path

# SNS
SNS: true
SNS-icon: #['Facebook', 'weibo', 'qq', 'github', 'Dribbble', 'Twitter', 'instagram', 'weixin', 'Codepen']
  mail: 'mailto:903729210@qq.com'
  weixin: 'https://u.wechat.com/MIo5usQ6XFUC8hIxKUGpSWo' # 你的微信二维码存放的地址
  qq: "https://qm.qq.com/cgi-bin/qm/qr?k=DH4YfUJjtW7Hydqq0z1Ax8AuMq3LtrC2&noverify=0&personal_qrcode_source=3" # 你的qq二维码存放的地址 or http://wpa.qq.com/msgrd?v=3&uin='你的QQ号'&site=qq&menu=yes
  #github: ''
  #Codepen: ''
  #weibo: ''
  #instagram: ''
  #Twitter: ''
  #Dribbble: ''
  #Facebook: ''
  #Google: ''
  #zhihu: ''
  #juejin: ''
  #twitch: ''

# 分页
paginate: 10
paginatepath: ['page:num']

# since
footer:
  since: 2022

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# 代码高亮 使用rouge
highlighter: rouge
# 代码高亮主题使用pygments主题: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango 任选一个你喜欢的主题名称填在下面的单引号中
pygmentsTheme: 'tango'

# 友情链接
friends:
  jekyll: 'https://www.jekyll.com.cn/'

# 评论 最佳体验 在disqus、livere和Gitment之间三选一
# disqus 评论
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# 来必力评论
livere: false
livere_uid: 'MTAyMC8zNDI2OS8xMDgwNg==' # MTAyMC8zNDI2OS8xMDgwNg==
# Gitment评论 OAuth Application
Gitment: false
Gitment_owner: ''  # github用户名
Gitment_repo: ''  # github博客存放的仓库名
client_id: ''  # 注册 OAuth Application 后获得的 client_id
client_secret: ''  # 注册 OAuth Application 后获得的 client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['qq', 'qzone', 'wechat', 'weibo', 'twitter', 'facebook']

# 百度统计 在baidu-url里填写自己相关的url代码
baidu: false
baidu-url: ''
# 谷歌分析 在google-ID里填写自己在谷歌分析获得的追踪ID
google: false
google-ID: ''

# 博客头信息备选颜色（该部分在站点中不充当站点变量，将其写在post的头信息中用来充当页面变量）
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)

plugins:
  - jekyll-paginate
  - jemoji